# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MindmapsDB Documentation
email: info@mindmaps.io
description: > # this means to ignore newlines until "baseurl:"
  MindmapsDB Documentation
baseurl: "/docs"
url: "http://mindmaps.io"
twitter_username: mindmapsdb
github_username: mindmapsdb

# Build settings
markdown: kramdown
